project_id: ##
region: us-east1                 

bronze:
  bucket: bronze-layer-bucket-2025
  artifact_repo: bronze-artifacts
  container_image: us-east1-docker.pkg.dev/##/bronze-artifacts/bronze-job
  job_name: bronze-job
