name: Create GCP Resources

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'Globally unique GCS bucket name'
        required: true
        type: string
      artifact_repo:
        description: 'Artifact Registry repository name'
        required: true
        type: string
  push:
    paths:
      - 'bronze_layer/**'

jobs:
  create-resources:
    runs-on: ubuntu-latest

    steps:
    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Create GCS Bucket (if not exists)
      run: |
        BUCKET_NAME="${{ github.event.inputs.bucket_name }}"
        REGION="${{ secrets.GCP_REGION }}"
        if gsutil ls -b gs://$BUCKET_NAME 2>/dev/null; then
          echo "GCS Bucket already exists: $BUCKET_NAME"
        else
          echo "Creating GCS Bucket: $BUCKET_NAME"
          gcloud storage buckets create gs://$BUCKET_NAME --location=$REGION
        fi

    - name: Create default data/ folder in GCS Bucket
      run: |
        BUCKET_NAME="${{ github.event.inputs.bucket_name }}"
        echo "placeholder" | gsutil cp - gs://$BUCKET_NAME/data/.keep

    - name: Create Artifact Registry repo (if not exists)
      run: |
        REPO_NAME="${{ github.event.inputs.artifact_repo }}"
        REGION="${{ secrets.GCP_REGION }}"
        PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}"

        if gcloud artifacts repositories list --location=$REGION | grep $REPO_NAME; then
          echo "Artifact repo already exists: $REPO_NAME"
        else
          echo "Creating Artifact Registry repo: $REPO_NAME"
          gcloud artifacts repositories create $REPO_NAME \
            --repository-format=docker \
            --location=$REGION \
            --description="Docker repo for Bronze layer"
        fi
