name: Create GCP Resources

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'Globally unique GCS bucket name'
        required: true
        type: string
      artifact_repo:
        description: 'Artifact Registry repository name'
        required: true
        type: string
  push:
    paths:
      - 'bronze_layer/**'

jobs:
  create-resources:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Create JSON credentials file
      id: create-json
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "gcloud-service-key.json"
        json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Authenticate with GCP
      run: gcloud auth activate-service-account --key-file=gcloud-service-key.json

    - name: Enable Artifact Registry API
      run: |
        if ! gcloud services list --enabled | grep -q artifactregistry.googleapis.com; then
          echo "Artifact Registry API is not enabled. Enabling it now..."
          gcloud services enable artifactregistry.googleapis.com
        else
          echo "Artifact Registry API is already enabled."
        fi

    - name: Check if Artifact Registry Repository exists
      id: check-repo
      run: |
        REPO="bronze-artifacts"
        REGION="${{ secrets.GCP_REGION }}"
        if gcloud artifacts repositories describe $REPO --location=$REGION; then
          echo "repo_exists=true" >> $GITHUB_ENV
        else
          echo "repo_exists=false" >> $GITHUB_ENV
        fi

    - name: Create Artifact Registry Repository
      if: env.repo_exists == 'false'
      run: |
        gcloud artifacts repositories create bronze-artifacts \
          --repository-format=docker \
          --location=${{ secrets.GCP_REGION }} \
          --description="Docker repository for Bronze Layer"

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bronze-artifacts/my-app:latest"
        docker build -t $IMAGE ./bronze_layer
        docker push $IMAGE

    - name: Create or Update Cloud Run Job
      run: |
        JOB_NAME="bronze-job"
        REGION="${{ secrets.GCP_REGION }}"
        IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bronze-artifacts/my-app:latest"

        if gcloud run jobs describe $JOB_NAME --region=$REGION > /dev/null 2>&1; then
          echo "Updating Cloud Run Job: $JOB_NAME"
          gcloud run jobs update $JOB_NAME \
            --image=$IMAGE \
            --region=$REGION \
            --memory=16Gi \
            --cpu=4
        else
          echo "Creating Cloud Run Job: $JOB_NAME"
          gcloud run jobs create $JOB_NAME \
            --image=$IMAGE \
            --region=$REGION \
            --memory=16Gi \
            --cpu=4
        fi
