name: Create GCP Resources
 
on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create JSON credentials file
      id: create-json-credentials
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "gcloud-service-key.json"
        json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
        scopes: https://www.googleapis.com/auth/bigquery  # Adding BigQuery full access


    - name: Authenticate to Google Cloud
      run: gcloud auth activate-service-account --key-file=gcloud-service-key.json

    - name: Create GCS bucket
      run: gcloud storage buckets create igbucket --location=us-central1

    - name: Create BigQuery Dataset and Table
      run: |
        bq mk --location=us-central1 nyc_subway_data
        bq mk --table nyc_subway_data.hourly_trip_data \
        "transit_timestamp:TIMESTAMP, \
        transit_mode:STRING, \
        station_complex_id:STRING, \
        station_complex:STRING, \
        borough:STRING, \
        payment_method:STRING, \
        fare_class_category:STRING, \
        ridership:FLOAT, \
        transfers:FLOAT, \
        latitude:FLOAT, \
        longitude:FLOAT"

    # # Step 3: Create a GCP VM instance with n1-standard-2 machine type
    # - name: Create GCP VM
    #   run: |
    #     gcloud compute instances create "bulk-ingest-instance" \
    #       --zone "us-central1-a" \
    #       --machine-type "n2-standard-2" \
    #       --image-project "debian-cloud" \
    #       --image-family "debian-11" \
    #       --boot-disk-size "100GB" \
    #       --scopes=https://www.googleapis.com/auth/cloud-platform \
    #       --metadata=startup-script='#!/bin/bash
    #         sudo apt-get update
    #         sudo apt-get install -y python3 python3-pip git'

    # # Step 4: SSH into the VM, clone the repo, and run the Python script
    # - name: Run Python Script on GCP VM
    #   run: |
    #     # Wait for the VM to initialize
    #     sleep 60
        
    #     # SSH into the VM and execute the necessary steps
    #     gcloud compute ssh "bulk-ingest-instance" --zone="us-central1-a" --command='
    #       git clone https://github.com/bharatp666/NYCSubwayAnalytics.git &&
    #       cd NYCSubwayAnalytics &&
    #       pip3 install -r requirements.txt &&
    #       cd Ingestion
    #       python3 bulk_ingest.py --project_id ${{ secrets.GCP_PROJECT_ID }}
   
        
    # # Step 5: Delete the GCP VM instance (Optional, cleanup)
    # - name: Delete GCP VM
    #   run: |
    #     gcloud compute instances delete "bulk-ingest-instance" --zone="us-central1-a" --quiet
