name: Deploy to GCS


on:
  workflow_dispatch:
  push:
    paths:
        - 'silver_layer/spark_main.py'              
        - 'silver_layer/spark_utility.py'
        - 'silver_layer/dataproc_init.sh'
        - 'silver_layer/logger_spark.py'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:

        - name: code checkout
          uses: actions/checkout@v2
        
        - name: Create JSON credentials file
          id: create-json-credentials
          uses: jsdaniell/create-json@v1.2.3
          with:
            name: "gcloud-service-key.json"
            json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    
        - name: install the gcloud cli
          uses: google-github-actions/setup-gcloud@v1
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
            export_default_credentials: true

        - name: Authenticate gcloud CLI explicitly
          run: |
              gcloud auth activate-service-account --key-file=gcloud-service-key.json
              gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          

        - name: Read config and deploy to GCS
          run: |
            echo "Reading second bucket info from config..."
            
            BUCKET=$(jq -r '.buckets[1].name' bucket_config.json)
            FOLDER=$(jq -r '.buckets[1].folders[0]' bucket_config.json)
            
            echo "Testing authentication with GCS..."
            gsutil ls gs://$BUCKET/
        
            echo "Deploying files from 'silver_layer/' to GCS bucket..."
            gsutil -m rsync -r "silver_layer/" gs://$BUCKET/$FOLDER/

