name: Execute Cloud Run Job 

on:
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Read config file into variables
        id: read_config
        run: |
          BUCKET=$(jq -r '.bucket' ingest_run_config.json)
          FOLDER=$(jq -r '.folder' ingest_run_config.json)
          N_JOBS=$(jq -r '.n_jobs' ingest_run_config.json)

          echo "BUCKET=$BUCKET" >> $GITHUB_ENV
          echo "FOLDER=$FOLDER" >> $GITHUB_ENV
          echo "N_JOBS=$N_JOBS" >> $GITHUB_ENV

      - name: Create JSON credentials file
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "gcloud-service-key.json"
          json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: "beta"  # optional
          export_default_credentials: false  # since you're authenticating manually

      - name: Authenticate to Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=gcloud-service-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region ${{ secrets.GCP_REGION }}

      - name: Execute Cloud Run Job with runtime args
        run: |
          gcloud run jobs execute bronze-job \
            --args="--bucket=${BUCKET},--folder=${FOLDER},--n_jobs=${N_JOBS}" \
            --wait
