name: Execute Cloud Run Job 

on:
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Read config file into environment variables
        run: |
          BUCKET_NAME=$(jq -r '.BUCKET_NAME' ingest_run_config.json)
          FOLDER_NAME=$(jq -r '.FOLDER_NAME' ingest_run_config.json)
          N_JOBS=$(jq -r '.N_JOBS' ingest_run_config.json)

          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
          echo "FOLDER_NAME=$FOLDER_NAME" >> $GITHUB_ENV
          echo "N_JOBS=$N_JOBS" >> $GITHUB_ENV

      - name: Create JSON credentials file
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "gcloud-service-key.json"
          json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: false

      - name: Authenticate to Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=gcloud-service-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region ${{ secrets.GCP_REGION }}

      - name: Execute Cloud Run Job
        run: |
          gcloud run jobs execute bronze-job \
            --region=${{ secrets.GCP_REGION }} \
            --wait
