name: Run Bronze Layer

on:
  workflow_run:
    workflows: ["Create GCP Resources"]
    types:
      - completed
jobs:
  execute-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create JSON credentials file
      id: create-json
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "gcloud-service-key.json"
        json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Authenticate with Google Cloud
      run: gcloud auth activate-service-account --key-file=gcloud-service-key.json

    - name: Install gcloud beta component
      run: gcloud components install beta --quiet

    - name: Execute Cloud Run Job
      run: |
        gcloud beta run jobs execute bronze-job --region=${{ secrets.GCP_REGION }}
